name: 'Eslint Fix Git Action'
author: 'Tugay İlik'
description: 'Runs "eslint --fix" command and commits the changes for fixable errors for changed files only.'
inputs:
  owner:
    description: 'The owner of the repository'
    required: true
  repo:
    description: 'The name of the repository'
    required: true
  pr_number:
    description: 'The number of the pull request'
    required: true
  token:
    description: 'The token to use to access the GitHub API'
    required: true
runs:
  using: 'node16'
  main: 'index.js'
