name: Eslint Fix

on: [push, pull_request]

jobs:
  eslint-fix-commit:
    runs-on: ubuntu-latest
    name: Fixes eslint issues on changed files only
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Annotate PR
        uses: ../../dist/index.js
        with:
          owner: ${{ github.repository_owner }}
          repo: ${{ github.event.repository.name }}
          pr_number: ${{ github.event.number }}
          token: ${{ secrets.GITHUB_TOKEN }}
